# Generated by Django 5.1.1 on 2024-09-13 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterIncharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CropType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('eligible_qty', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DDR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('delivery_location', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('cluster_incharge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddr.clusterincharge')),
                ('crop_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddr.croptype')),
            ],
        ),
        migrations.CreateModel(
            name='DDRFarmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddr_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ddr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddr.ddr')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddr.farmer')),
            ],
        ),
        migrations.AddField(
            model_name='ddr',
            name='farmer',
            field=models.ManyToManyField(through='ddr.DDRFarmer', to='ddr.farmer'),
        ),
        migrations.AddField(
            model_name='ddr',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddr.source'),
        ),
        migrations.AddField(
            model_name='ddr',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddr.variety'),
        ),
    ]
